# .terraform-docs.yml
recursive:
  enabled: true
  path: .

output:
  file: "README.md"
  mode: replace

formatter: "markdown table"

content: |-
  ## Terraform modules
  This repository contains terraform modules for our project